ci: use xvfb for testing on Linux

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -148,7 +148,7 @@ jobs:
 
       - name: Set up X11
         if: matrix.os == 'ubuntu-latest'
-        run: sudo apt-get install --yes --no-install-recommends libx11-dev
+        run: sudo apt-get install --yes --no-install-recommends libx11-dev xvfb xauth
 
       - name: Set up Lua
         uses: luarocks/gh-actions-lua@master
@@ -162,7 +162,12 @@ jobs:
         run: luarocks make
 
       - name: Run tests
-        run: luarocks test -- --exclude-tags needsdisplay --verbose --output TAP
+        run: >-
+          ${{
+          matrix.os == 'ubuntu-latest'
+          && 'trap "cat /tmp/xvfb-run-error.txt && rm --force /tmp/xvfb-run-error.txt" EXIT INT TERM QUIT; xvfb-run --auto-servernum --error-file=/tmp/xvfb-run-error.txt luarocks test -- --verbose --output TAP'
+          || 'luarocks test -- --exclude-tags needsdisplay --verbose --output TAP'
+          }}
 
 
   test-docker:
@@ -180,7 +185,6 @@ jobs:
 
       - name: Run Tests in Docker
         env:
-          EXCLUDE_TAGS: needsdisplay
           # renovate: datasource=github-releases depName=docker/compose
           COMPOSE_VERSION: v2.34.0
         run: |
